export const KEY_PUBLIC = 'a5837db97d72016c81a7a776f4240db9'
export const CHARS = 'characters'
export const COMICS = 'comics'
export const MAX_SIZE = 'landscape_incredible'
export const PORTRATE = 'portrait_uncanny'
export const PORTRATE_MEDIUM = 'portrait_medium'
export const NO_PIC = 'image_not_available'
